name: "Xanitizer Security Analysis"

on:
  push:
    branches: [ main ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main ]
  schedule:
    - cron: '16 22 * * 2'
  workflow_dispatch:

jobs:
  xanitizer-security-analysis:
    # Xanitizer runs on and windows-latest.
    runs-on: windows-latest

    steps:
      # Check out the repository
      - name: Checkout
        uses: actions/checkout@v2

      # Set up the correct Java version for your project
      # Please comment out, if your project does not contain Java source code.
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      # Compile the code for Java projects and get all libraries, e.g. via Maven
      # Please adapt, if your project uses another build system to compile Java source code.
      # Please comment out, if your project does not contain Java source code.
      - name: Compile Java code
        run: mvn -B compile

      # Install all dependent libraries for JavaScript/TypeScript projects, e.g. via npm
      # Please adapt to run `npm install` in the correct directories.
      # Please adapt, if your project uses another package manager for getting JavaScript libraries.
      # Please comment out, if your project does not use a package manager for getting JavaScript libraries.
      - name: Install JavaScript libraries
        run: install

      # Run the security analysis with default settings
      - name: Xanitizer Security Analysis
        uses: RIGS-IT/xanitizer-action@v1
        with:
          license: ${{ secrets.XANITIZER_LICENSE }}

      # Archiving the findings list reports
      - uses: actions/upload-artifact@v2
        with:
          name: Xanitizer-Reports
          path: |
            *-Findings-List.pdf
            *-Findings-List.sarif

      # Uploads the findings into the GitHub code scanning alert section using the upload-sarif action
      - uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: SECURITY.md
